
import { GoogleGenAI, Type } from "@google/genai";

const getAI = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

export const analyzeImageForPost = async (base64Image: string, mimeType: string) => {
  const ai = getAI();
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType,
            data: base64Image,
          },
        },
        {
          text: "Analyze this image and suggest a catchy title, a short engaging description, 3-5 relevant tags, and pick the best category from: Tech, News, Lifestyle, Gaming, Nature. Return as JSON.",
        },
      ],
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          title: { type: Type.STRING },
          description: { type: Type.STRING },
          category: { type: Type.STRING },
          tags: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
          },
        },
        required: ["title", "description", "tags"],
      },
    },
  });

  const jsonStr = response.text?.trim();
  if (!jsonStr) throw new Error("No content generated by AI");
  return JSON.parse(jsonStr);
};

export const suggestFunnyCaption = async (title: string, context: string, imageBase64?: string) => {
  const ai = getAI();
  const parts: any[] = [{ text: `Generate a funny, witty caption or a joke related to this content. Title: ${title}, Description: ${context}. Return just the text, under 100 characters.` }];
  
  if (imageBase64) {
    parts.push({
      inlineData: {
        mimeType: 'image/jpeg',
        data: imageBase64,
      },
    });
  }

  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: { parts },
  });
  return response.text?.trim() || "Just another signal in the cluster.";
};

export const suggestFunnyComment = async (postContent: string) => {
  const ai = getAI();
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: `Suggest a short, funny, slightly sarcastic comment for this post: "${postContent}". Just the text, no quotes.`,
  });
  return response.text?.trim() || "Interesting transmission...";
};

export const suggestKeywords = async (text: string) => {
  const ai = getAI();
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: `Based on this text: "${text}", suggest 5 relevant hashtags or keywords. Return as a comma-separated list.`,
  });
  return response.text?.trim() || "";
};
